<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shashank" failures="1" tests="5" name="Listener testcase" time="0.096" errors="0" timestamp="2024-06-03T19:53:12 IST">
  <testcase classname="TestNGListeners.SampleTest" name="TestFour" time="0.009">
    <skipped/>
  </testcase> <!-- TestFour -->
  <testcase classname="TestNGListeners.SampleTest" name="TestThree" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at TestNGListeners.SampleTest.TestThree(SampleTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- TestThree -->
  <testcase classname="TestNGListeners.SampleTest" name="testGetData" time="0.002"/>
  <testcase classname="TestNGListeners.SampleTest" name="testGetData" time="0.001"/>
  <testcase classname="TestNGListeners.SampleTest" name="testOne" time="0.002"/>
</testsuite> <!-- Listener testcase -->
